import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter as FontSans } from "next/font/google"
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import Provider from "./Provider";
import { UploadContextProvider } from "@/components/upload/UploadContext";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <UploadContextProvider>
            <Provider>
              <>
                <Navbar />
                {children}
              </>
            </Provider>
          </UploadContextProvider>
        </ThemeProvider>

        <Toaster />

      </body>
    </html>
  );
}
